services:
  db:
    image: postgres:16  # Kunci di versi 16 supaya aman
    restart: always
    environment:
      - POSTGRES_USER=admin_resto
      - POSTGRES_PASSWORD=rahasia123
      - POSTGRES_DB=yum_resto_db
    ports:
      - 5432:5432
    volumes:
      - ./data_baru:/var/lib/postgresql/data # Pakai nama folder baru